---
- hosts: all
  remote_user: root
  always_run: yes
  tasks:
    - name: Write the Hostname to File
      shell: echo "{{ host_name }}" > /etc/hostname

    - name: Apply Hostname
      shell: hostname -F /etc/hostname

    - name: Add Local DNS Resolution for our Hostname
      lineinfile: dest=/etc/hosts line="127.0.1.1    {{ host_name }}" regexp=^.*127.0.1.1