- hosts: all
  roles:
     - role: dj-wasabi.zabbix-agent
       zabbix_agent_server: {{ zabbix_server_ip }}
       zabbix_agent_serveractive: {{ zabbix_server_ip }}
       zabbix_url: {{ zabbix_url }}
       zabbix_api_use: false # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux